org: mirandasalazar
service: sismos-scrapping

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::060098569939:role/LabRole
  ecr:
    images:
      lambda-selenium:
        path: ./

functions:
  sismos:
    image:
      name: lambda-selenium
      command: ["sismos.lambda_handler"]

package:
  exclude:
    - node_modules/**
    - selenium-layer/**

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Sismostry2
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST