org: mirandasalazar
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  # Default memory size for functions (default: 1024MB)
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::060098569939:role/LabRole

functions:
  scrape_table:
    image:
      name: lambda-imag
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true
resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Sismostry2
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
